name: Build and Test Ansible Execution Environment

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - develop

jobs:
  build:
    runs-on: arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5
        with:
          files: |
            execution-environments/**/VERSION

      - name: Install ansible-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install --upgrade pip
          pip install ansible-dev-tools
          
      - name: Build Ansible Execution Environment
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            dir=$(dirname "$file")
            ee_version=$(sed -n '2p' "$dir/VERSION")
            ee_name=$(basename "$dir")
            echo "Building execution environment for $ee_name version $ee_version"
            cd $dir
            /home/runner/.local/bin/ansible-builder build \
              --container-runtime docker \
              --tag "$ee_name:$ee_version" \
              --verbosity 3
            break
          done