name: Build and Test Ansible Execution Environment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5
        with:
          files: |
            execution-environments/**/VERSION

      - name: Install ansible-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install --upgrade pip
          pip install ansible-dev-tools
      
      - name: Install docker
        run: |
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Build Ansible Execution Environment
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            dir=$(dirname "$file")
            ee_version=$(sed -n '2p' "$dir/VERSION")
            ee_name=$(basename "$dir")
            echo "Building execution environment for $ee_name version $ee_version"
            cd $dir
            sudo service docker start
            /home/runner/.local/bin/ansible-builder build \
              --container-runtime docker \
              --tag "$ee_name:$ee_version" \
              --verbosity 3
            break
          done